M48
; DRILL file {KiCad 6.0.0} date Sun Jan 30 15:16:09 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-30T15:16:09-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.630
%
G90
G05
T1
X162.825Y-68.425
T2
X162.825Y-68.425
X168.825Y-68.425
T0
M30
